// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `AGMCommonBehavior.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <AGMCommonBehavior.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/BasicStream.h>
#include <Ice/Object.h>
#include <IceUtil/Iterator.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace
{

const ::std::string __RoboCompAGMCommonBehavior__AGMCommonBehavior__activateAgent_name = "activateAgent";

const ::std::string __RoboCompAGMCommonBehavior__AGMCommonBehavior__deactivateAgent_name = "deactivateAgent";

const ::std::string __RoboCompAGMCommonBehavior__AGMCommonBehavior__getAgentState_name = "getAgentState";

const ::std::string __RoboCompAGMCommonBehavior__AGMCommonBehavior__getAgentParameters_name = "getAgentParameters";

const ::std::string __RoboCompAGMCommonBehavior__AGMCommonBehavior__setAgentParameters_name = "setAgentParameters";

const ::std::string __RoboCompAGMCommonBehavior__AGMCommonBehavior__killAgent_name = "killAgent";

const ::std::string __RoboCompAGMCommonBehavior__AGMCommonBehavior__uptimeAgent_name = "uptimeAgent";

const ::std::string __RoboCompAGMCommonBehavior__AGMCommonBehavior__reloadConfigAgent_name = "reloadConfigAgent";

}

namespace Ice
{
}
::IceProxy::Ice::Object* ::IceProxy::RoboCompAGMCommonBehavior::upCast(::IceProxy::RoboCompAGMCommonBehavior::AGMCommonBehavior* p) { return p; }

void
::IceProxy::RoboCompAGMCommonBehavior::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::RoboCompAGMCommonBehavior::AGMCommonBehavior>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::RoboCompAGMCommonBehavior::AGMCommonBehavior;
        v->__copyFrom(proxy);
    }
}

bool
IceProxy::RoboCompAGMCommonBehavior::AGMCommonBehavior::activateAgent(const ::RoboCompAGMCommonBehavior::ParameterMap& prs, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __RoboCompAGMCommonBehavior__AGMCommonBehavior__activateAgent_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__RoboCompAGMCommonBehavior__AGMCommonBehavior__activateAgent_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::RoboCompAGMCommonBehavior::AGMCommonBehavior* __del = dynamic_cast< ::IceDelegate::RoboCompAGMCommonBehavior::AGMCommonBehavior*>(__delBase.get());
            return __del->activateAgent(prs, __ctx, __observer);
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::RoboCompAGMCommonBehavior::AGMCommonBehavior::begin_activateAgent(const ::RoboCompAGMCommonBehavior::ParameterMap& prs, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__RoboCompAGMCommonBehavior__AGMCommonBehavior__activateAgent_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RoboCompAGMCommonBehavior__AGMCommonBehavior__activateAgent_name, __del, __cookie);
    try
    {
        __result->__prepare(__RoboCompAGMCommonBehavior__AGMCommonBehavior__activateAgent_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(prs);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

bool
IceProxy::RoboCompAGMCommonBehavior::AGMCommonBehavior::end_activateAgent(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __RoboCompAGMCommonBehavior__AGMCommonBehavior__activateAgent_name);
    bool __ret;
    bool __ok = __result->__wait();
    try
    {
        if(!__ok)
        {
            try
            {
                __result->__throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
            }
        }
        ::IceInternal::BasicStream* __is = __result->__startReadParams();
        __is->read(__ret);
        __result->__endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& ex)
    {
        __result->__getObserver().failed(ex.ice_name());
        throw;
    }
}

bool
IceProxy::RoboCompAGMCommonBehavior::AGMCommonBehavior::deactivateAgent(const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __RoboCompAGMCommonBehavior__AGMCommonBehavior__deactivateAgent_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__RoboCompAGMCommonBehavior__AGMCommonBehavior__deactivateAgent_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::RoboCompAGMCommonBehavior::AGMCommonBehavior* __del = dynamic_cast< ::IceDelegate::RoboCompAGMCommonBehavior::AGMCommonBehavior*>(__delBase.get());
            return __del->deactivateAgent(__ctx, __observer);
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::RoboCompAGMCommonBehavior::AGMCommonBehavior::begin_deactivateAgent(const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__RoboCompAGMCommonBehavior__AGMCommonBehavior__deactivateAgent_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RoboCompAGMCommonBehavior__AGMCommonBehavior__deactivateAgent_name, __del, __cookie);
    try
    {
        __result->__prepare(__RoboCompAGMCommonBehavior__AGMCommonBehavior__deactivateAgent_name, ::Ice::Normal, __ctx);
        __result->__writeEmptyParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

bool
IceProxy::RoboCompAGMCommonBehavior::AGMCommonBehavior::end_deactivateAgent(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __RoboCompAGMCommonBehavior__AGMCommonBehavior__deactivateAgent_name);
    bool __ret;
    bool __ok = __result->__wait();
    try
    {
        if(!__ok)
        {
            try
            {
                __result->__throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
            }
        }
        ::IceInternal::BasicStream* __is = __result->__startReadParams();
        __is->read(__ret);
        __result->__endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& ex)
    {
        __result->__getObserver().failed(ex.ice_name());
        throw;
    }
}

::RoboCompAGMCommonBehavior::StateStruct
IceProxy::RoboCompAGMCommonBehavior::AGMCommonBehavior::getAgentState(const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __RoboCompAGMCommonBehavior__AGMCommonBehavior__getAgentState_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__RoboCompAGMCommonBehavior__AGMCommonBehavior__getAgentState_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::RoboCompAGMCommonBehavior::AGMCommonBehavior* __del = dynamic_cast< ::IceDelegate::RoboCompAGMCommonBehavior::AGMCommonBehavior*>(__delBase.get());
            return __del->getAgentState(__ctx, __observer);
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::RoboCompAGMCommonBehavior::AGMCommonBehavior::begin_getAgentState(const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__RoboCompAGMCommonBehavior__AGMCommonBehavior__getAgentState_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RoboCompAGMCommonBehavior__AGMCommonBehavior__getAgentState_name, __del, __cookie);
    try
    {
        __result->__prepare(__RoboCompAGMCommonBehavior__AGMCommonBehavior__getAgentState_name, ::Ice::Normal, __ctx);
        __result->__writeEmptyParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

::RoboCompAGMCommonBehavior::StateStruct
IceProxy::RoboCompAGMCommonBehavior::AGMCommonBehavior::end_getAgentState(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __RoboCompAGMCommonBehavior__AGMCommonBehavior__getAgentState_name);
    ::RoboCompAGMCommonBehavior::StateStruct __ret;
    bool __ok = __result->__wait();
    try
    {
        if(!__ok)
        {
            try
            {
                __result->__throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
            }
        }
        ::IceInternal::BasicStream* __is = __result->__startReadParams();
        __is->read(__ret);
        __result->__endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& ex)
    {
        __result->__getObserver().failed(ex.ice_name());
        throw;
    }
}

::RoboCompAGMCommonBehavior::ParameterMap
IceProxy::RoboCompAGMCommonBehavior::AGMCommonBehavior::getAgentParameters(const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __RoboCompAGMCommonBehavior__AGMCommonBehavior__getAgentParameters_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__RoboCompAGMCommonBehavior__AGMCommonBehavior__getAgentParameters_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::RoboCompAGMCommonBehavior::AGMCommonBehavior* __del = dynamic_cast< ::IceDelegate::RoboCompAGMCommonBehavior::AGMCommonBehavior*>(__delBase.get());
            return __del->getAgentParameters(__ctx, __observer);
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::RoboCompAGMCommonBehavior::AGMCommonBehavior::begin_getAgentParameters(const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__RoboCompAGMCommonBehavior__AGMCommonBehavior__getAgentParameters_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RoboCompAGMCommonBehavior__AGMCommonBehavior__getAgentParameters_name, __del, __cookie);
    try
    {
        __result->__prepare(__RoboCompAGMCommonBehavior__AGMCommonBehavior__getAgentParameters_name, ::Ice::Normal, __ctx);
        __result->__writeEmptyParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

::RoboCompAGMCommonBehavior::ParameterMap
IceProxy::RoboCompAGMCommonBehavior::AGMCommonBehavior::end_getAgentParameters(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __RoboCompAGMCommonBehavior__AGMCommonBehavior__getAgentParameters_name);
    ::RoboCompAGMCommonBehavior::ParameterMap __ret;
    bool __ok = __result->__wait();
    try
    {
        if(!__ok)
        {
            try
            {
                __result->__throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
            }
        }
        ::IceInternal::BasicStream* __is = __result->__startReadParams();
        __is->read(__ret);
        __result->__endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& ex)
    {
        __result->__getObserver().failed(ex.ice_name());
        throw;
    }
}

bool
IceProxy::RoboCompAGMCommonBehavior::AGMCommonBehavior::setAgentParameters(const ::RoboCompAGMCommonBehavior::ParameterMap& prs, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __RoboCompAGMCommonBehavior__AGMCommonBehavior__setAgentParameters_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__RoboCompAGMCommonBehavior__AGMCommonBehavior__setAgentParameters_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::RoboCompAGMCommonBehavior::AGMCommonBehavior* __del = dynamic_cast< ::IceDelegate::RoboCompAGMCommonBehavior::AGMCommonBehavior*>(__delBase.get());
            return __del->setAgentParameters(prs, __ctx, __observer);
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::RoboCompAGMCommonBehavior::AGMCommonBehavior::begin_setAgentParameters(const ::RoboCompAGMCommonBehavior::ParameterMap& prs, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__RoboCompAGMCommonBehavior__AGMCommonBehavior__setAgentParameters_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RoboCompAGMCommonBehavior__AGMCommonBehavior__setAgentParameters_name, __del, __cookie);
    try
    {
        __result->__prepare(__RoboCompAGMCommonBehavior__AGMCommonBehavior__setAgentParameters_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(prs);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

bool
IceProxy::RoboCompAGMCommonBehavior::AGMCommonBehavior::end_setAgentParameters(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __RoboCompAGMCommonBehavior__AGMCommonBehavior__setAgentParameters_name);
    bool __ret;
    bool __ok = __result->__wait();
    try
    {
        if(!__ok)
        {
            try
            {
                __result->__throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
            }
        }
        ::IceInternal::BasicStream* __is = __result->__startReadParams();
        __is->read(__ret);
        __result->__endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& ex)
    {
        __result->__getObserver().failed(ex.ice_name());
        throw;
    }
}

void
IceProxy::RoboCompAGMCommonBehavior::AGMCommonBehavior::killAgent(const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __RoboCompAGMCommonBehavior__AGMCommonBehavior__killAgent_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __delBase = __getDelegate(false);
            ::IceDelegate::RoboCompAGMCommonBehavior::AGMCommonBehavior* __del = dynamic_cast< ::IceDelegate::RoboCompAGMCommonBehavior::AGMCommonBehavior*>(__delBase.get());
            __del->killAgent(__ctx, __observer);
            return;
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::RoboCompAGMCommonBehavior::AGMCommonBehavior::begin_killAgent(const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RoboCompAGMCommonBehavior__AGMCommonBehavior__killAgent_name, __del, __cookie);
    try
    {
        __result->__prepare(__RoboCompAGMCommonBehavior__AGMCommonBehavior__killAgent_name, ::Ice::Normal, __ctx);
        __result->__writeEmptyParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

void
IceProxy::RoboCompAGMCommonBehavior::AGMCommonBehavior::end_killAgent(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __RoboCompAGMCommonBehavior__AGMCommonBehavior__killAgent_name);
}

::Ice::Int
IceProxy::RoboCompAGMCommonBehavior::AGMCommonBehavior::uptimeAgent(const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __RoboCompAGMCommonBehavior__AGMCommonBehavior__uptimeAgent_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__RoboCompAGMCommonBehavior__AGMCommonBehavior__uptimeAgent_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::RoboCompAGMCommonBehavior::AGMCommonBehavior* __del = dynamic_cast< ::IceDelegate::RoboCompAGMCommonBehavior::AGMCommonBehavior*>(__delBase.get());
            return __del->uptimeAgent(__ctx, __observer);
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::RoboCompAGMCommonBehavior::AGMCommonBehavior::begin_uptimeAgent(const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__RoboCompAGMCommonBehavior__AGMCommonBehavior__uptimeAgent_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RoboCompAGMCommonBehavior__AGMCommonBehavior__uptimeAgent_name, __del, __cookie);
    try
    {
        __result->__prepare(__RoboCompAGMCommonBehavior__AGMCommonBehavior__uptimeAgent_name, ::Ice::Normal, __ctx);
        __result->__writeEmptyParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

::Ice::Int
IceProxy::RoboCompAGMCommonBehavior::AGMCommonBehavior::end_uptimeAgent(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __RoboCompAGMCommonBehavior__AGMCommonBehavior__uptimeAgent_name);
    ::Ice::Int __ret;
    bool __ok = __result->__wait();
    try
    {
        if(!__ok)
        {
            try
            {
                __result->__throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
            }
        }
        ::IceInternal::BasicStream* __is = __result->__startReadParams();
        __is->read(__ret);
        __result->__endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& ex)
    {
        __result->__getObserver().failed(ex.ice_name());
        throw;
    }
}

bool
IceProxy::RoboCompAGMCommonBehavior::AGMCommonBehavior::reloadConfigAgent(const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __RoboCompAGMCommonBehavior__AGMCommonBehavior__reloadConfigAgent_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__RoboCompAGMCommonBehavior__AGMCommonBehavior__reloadConfigAgent_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::RoboCompAGMCommonBehavior::AGMCommonBehavior* __del = dynamic_cast< ::IceDelegate::RoboCompAGMCommonBehavior::AGMCommonBehavior*>(__delBase.get());
            return __del->reloadConfigAgent(__ctx, __observer);
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::RoboCompAGMCommonBehavior::AGMCommonBehavior::begin_reloadConfigAgent(const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__RoboCompAGMCommonBehavior__AGMCommonBehavior__reloadConfigAgent_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RoboCompAGMCommonBehavior__AGMCommonBehavior__reloadConfigAgent_name, __del, __cookie);
    try
    {
        __result->__prepare(__RoboCompAGMCommonBehavior__AGMCommonBehavior__reloadConfigAgent_name, ::Ice::Normal, __ctx);
        __result->__writeEmptyParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

bool
IceProxy::RoboCompAGMCommonBehavior::AGMCommonBehavior::end_reloadConfigAgent(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __RoboCompAGMCommonBehavior__AGMCommonBehavior__reloadConfigAgent_name);
    bool __ret;
    bool __ok = __result->__wait();
    try
    {
        if(!__ok)
        {
            try
            {
                __result->__throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
            }
        }
        ::IceInternal::BasicStream* __is = __result->__startReadParams();
        __is->read(__ret);
        __result->__endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& ex)
    {
        __result->__getObserver().failed(ex.ice_name());
        throw;
    }
}

const ::std::string&
IceProxy::RoboCompAGMCommonBehavior::AGMCommonBehavior::ice_staticId()
{
    return ::RoboCompAGMCommonBehavior::AGMCommonBehavior::ice_staticId();
}

::IceInternal::Handle< ::IceDelegateM::Ice::Object>
IceProxy::RoboCompAGMCommonBehavior::AGMCommonBehavior::__createDelegateM()
{
    return ::IceInternal::Handle< ::IceDelegateM::Ice::Object>(new ::IceDelegateM::RoboCompAGMCommonBehavior::AGMCommonBehavior);
}

::IceInternal::Handle< ::IceDelegateD::Ice::Object>
IceProxy::RoboCompAGMCommonBehavior::AGMCommonBehavior::__createDelegateD()
{
    return ::IceInternal::Handle< ::IceDelegateD::Ice::Object>(new ::IceDelegateD::RoboCompAGMCommonBehavior::AGMCommonBehavior);
}

::IceProxy::Ice::Object*
IceProxy::RoboCompAGMCommonBehavior::AGMCommonBehavior::__newInstance() const
{
    return new AGMCommonBehavior;
}

bool
IceDelegateM::RoboCompAGMCommonBehavior::AGMCommonBehavior::activateAgent(const ::RoboCompAGMCommonBehavior::ParameterMap& prs, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __RoboCompAGMCommonBehavior__AGMCommonBehavior__activateAgent_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(prs);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    bool __ret;
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.startReadParams();
        __is->read(__ret);
        __og.endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

bool
IceDelegateM::RoboCompAGMCommonBehavior::AGMCommonBehavior::deactivateAgent(const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __RoboCompAGMCommonBehavior__AGMCommonBehavior__deactivateAgent_name, ::Ice::Normal, __context, __observer);
    __og.writeEmptyParams();
    bool __ok = __og.invoke();
    bool __ret;
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.startReadParams();
        __is->read(__ret);
        __og.endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

::RoboCompAGMCommonBehavior::StateStruct
IceDelegateM::RoboCompAGMCommonBehavior::AGMCommonBehavior::getAgentState(const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __RoboCompAGMCommonBehavior__AGMCommonBehavior__getAgentState_name, ::Ice::Normal, __context, __observer);
    __og.writeEmptyParams();
    bool __ok = __og.invoke();
    ::RoboCompAGMCommonBehavior::StateStruct __ret;
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.startReadParams();
        __is->read(__ret);
        __og.endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

::RoboCompAGMCommonBehavior::ParameterMap
IceDelegateM::RoboCompAGMCommonBehavior::AGMCommonBehavior::getAgentParameters(const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __RoboCompAGMCommonBehavior__AGMCommonBehavior__getAgentParameters_name, ::Ice::Normal, __context, __observer);
    __og.writeEmptyParams();
    bool __ok = __og.invoke();
    ::RoboCompAGMCommonBehavior::ParameterMap __ret;
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.startReadParams();
        __is->read(__ret);
        __og.endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

bool
IceDelegateM::RoboCompAGMCommonBehavior::AGMCommonBehavior::setAgentParameters(const ::RoboCompAGMCommonBehavior::ParameterMap& prs, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __RoboCompAGMCommonBehavior__AGMCommonBehavior__setAgentParameters_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(prs);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    bool __ret;
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.startReadParams();
        __is->read(__ret);
        __og.endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

void
IceDelegateM::RoboCompAGMCommonBehavior::AGMCommonBehavior::killAgent(const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __RoboCompAGMCommonBehavior__AGMCommonBehavior__killAgent_name, ::Ice::Normal, __context, __observer);
    __og.writeEmptyParams();
    bool __ok = __og.invoke();
    if(__og.hasResponse())
    {
        try
        {
            if(!__ok)
            {
                try
                {
                    __og.throwUserException();
                }
                catch(const ::Ice::UserException& __ex)
                {
                    ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                    throw __uue;
                }
            }
            __og.readEmptyParams();
        }
        catch(const ::Ice::LocalException& __ex)
        {
            throw ::IceInternal::LocalExceptionWrapper(__ex, false);
        }
    }
}

::Ice::Int
IceDelegateM::RoboCompAGMCommonBehavior::AGMCommonBehavior::uptimeAgent(const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __RoboCompAGMCommonBehavior__AGMCommonBehavior__uptimeAgent_name, ::Ice::Normal, __context, __observer);
    __og.writeEmptyParams();
    bool __ok = __og.invoke();
    ::Ice::Int __ret;
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.startReadParams();
        __is->read(__ret);
        __og.endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

bool
IceDelegateM::RoboCompAGMCommonBehavior::AGMCommonBehavior::reloadConfigAgent(const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __RoboCompAGMCommonBehavior__AGMCommonBehavior__reloadConfigAgent_name, ::Ice::Normal, __context, __observer);
    __og.writeEmptyParams();
    bool __ok = __og.invoke();
    bool __ret;
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.startReadParams();
        __is->read(__ret);
        __og.endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

bool
IceDelegateD::RoboCompAGMCommonBehavior::AGMCommonBehavior::activateAgent(const ::RoboCompAGMCommonBehavior::ParameterMap& prs, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(bool& __result, const ::RoboCompAGMCommonBehavior::ParameterMap& __p_prs, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _result(__result),
            _m_prs(__p_prs)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::RoboCompAGMCommonBehavior::AGMCommonBehavior* servant = dynamic_cast< ::RoboCompAGMCommonBehavior::AGMCommonBehavior*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            _result = servant->activateAgent(_m_prs, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        bool& _result;
        const ::RoboCompAGMCommonBehavior::ParameterMap& _m_prs;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __RoboCompAGMCommonBehavior__AGMCommonBehavior__activateAgent_name, ::Ice::Normal, __context);
    bool __result;
    try
    {
        _DirectI __direct(__result, prs, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
    return __result;
}

bool
IceDelegateD::RoboCompAGMCommonBehavior::AGMCommonBehavior::deactivateAgent(const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(bool& __result, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _result(__result)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::RoboCompAGMCommonBehavior::AGMCommonBehavior* servant = dynamic_cast< ::RoboCompAGMCommonBehavior::AGMCommonBehavior*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            _result = servant->deactivateAgent(_current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        bool& _result;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __RoboCompAGMCommonBehavior__AGMCommonBehavior__deactivateAgent_name, ::Ice::Normal, __context);
    bool __result;
    try
    {
        _DirectI __direct(__result, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
    return __result;
}

::RoboCompAGMCommonBehavior::StateStruct
IceDelegateD::RoboCompAGMCommonBehavior::AGMCommonBehavior::getAgentState(const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(::RoboCompAGMCommonBehavior::StateStruct& __result, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _result(__result)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::RoboCompAGMCommonBehavior::AGMCommonBehavior* servant = dynamic_cast< ::RoboCompAGMCommonBehavior::AGMCommonBehavior*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            _result = servant->getAgentState(_current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        ::RoboCompAGMCommonBehavior::StateStruct& _result;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __RoboCompAGMCommonBehavior__AGMCommonBehavior__getAgentState_name, ::Ice::Normal, __context);
    ::RoboCompAGMCommonBehavior::StateStruct __result;
    try
    {
        _DirectI __direct(__result, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
    return __result;
}

::RoboCompAGMCommonBehavior::ParameterMap
IceDelegateD::RoboCompAGMCommonBehavior::AGMCommonBehavior::getAgentParameters(const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(::RoboCompAGMCommonBehavior::ParameterMap& __result, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _result(__result)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::RoboCompAGMCommonBehavior::AGMCommonBehavior* servant = dynamic_cast< ::RoboCompAGMCommonBehavior::AGMCommonBehavior*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            _result = servant->getAgentParameters(_current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        ::RoboCompAGMCommonBehavior::ParameterMap& _result;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __RoboCompAGMCommonBehavior__AGMCommonBehavior__getAgentParameters_name, ::Ice::Normal, __context);
    ::RoboCompAGMCommonBehavior::ParameterMap __result;
    try
    {
        _DirectI __direct(__result, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
    return __result;
}

bool
IceDelegateD::RoboCompAGMCommonBehavior::AGMCommonBehavior::setAgentParameters(const ::RoboCompAGMCommonBehavior::ParameterMap& prs, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(bool& __result, const ::RoboCompAGMCommonBehavior::ParameterMap& __p_prs, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _result(__result),
            _m_prs(__p_prs)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::RoboCompAGMCommonBehavior::AGMCommonBehavior* servant = dynamic_cast< ::RoboCompAGMCommonBehavior::AGMCommonBehavior*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            _result = servant->setAgentParameters(_m_prs, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        bool& _result;
        const ::RoboCompAGMCommonBehavior::ParameterMap& _m_prs;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __RoboCompAGMCommonBehavior__AGMCommonBehavior__setAgentParameters_name, ::Ice::Normal, __context);
    bool __result;
    try
    {
        _DirectI __direct(__result, prs, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
    return __result;
}

void
IceDelegateD::RoboCompAGMCommonBehavior::AGMCommonBehavior::killAgent(const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::RoboCompAGMCommonBehavior::AGMCommonBehavior* servant = dynamic_cast< ::RoboCompAGMCommonBehavior::AGMCommonBehavior*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            servant->killAgent(_current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __RoboCompAGMCommonBehavior__AGMCommonBehavior__killAgent_name, ::Ice::Normal, __context);
    try
    {
        _DirectI __direct(__current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
}

::Ice::Int
IceDelegateD::RoboCompAGMCommonBehavior::AGMCommonBehavior::uptimeAgent(const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(::Ice::Int& __result, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _result(__result)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::RoboCompAGMCommonBehavior::AGMCommonBehavior* servant = dynamic_cast< ::RoboCompAGMCommonBehavior::AGMCommonBehavior*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            _result = servant->uptimeAgent(_current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        ::Ice::Int& _result;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __RoboCompAGMCommonBehavior__AGMCommonBehavior__uptimeAgent_name, ::Ice::Normal, __context);
    ::Ice::Int __result;
    try
    {
        _DirectI __direct(__result, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
    return __result;
}

bool
IceDelegateD::RoboCompAGMCommonBehavior::AGMCommonBehavior::reloadConfigAgent(const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(bool& __result, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _result(__result)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::RoboCompAGMCommonBehavior::AGMCommonBehavior* servant = dynamic_cast< ::RoboCompAGMCommonBehavior::AGMCommonBehavior*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            _result = servant->reloadConfigAgent(_current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        bool& _result;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __RoboCompAGMCommonBehavior__AGMCommonBehavior__reloadConfigAgent_name, ::Ice::Normal, __context);
    bool __result;
    try
    {
        _DirectI __direct(__result, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
    return __result;
}

::Ice::Object* RoboCompAGMCommonBehavior::upCast(::RoboCompAGMCommonBehavior::AGMCommonBehavior* p) { return p; }

namespace
{
const ::std::string __RoboCompAGMCommonBehavior__AGMCommonBehavior_ids[2] =
{
    "::Ice::Object",
    "::RoboCompAGMCommonBehavior::AGMCommonBehavior"
};

}

bool
RoboCompAGMCommonBehavior::AGMCommonBehavior::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__RoboCompAGMCommonBehavior__AGMCommonBehavior_ids, __RoboCompAGMCommonBehavior__AGMCommonBehavior_ids + 2, _s);
}

::std::vector< ::std::string>
RoboCompAGMCommonBehavior::AGMCommonBehavior::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__RoboCompAGMCommonBehavior__AGMCommonBehavior_ids[0], &__RoboCompAGMCommonBehavior__AGMCommonBehavior_ids[2]);
}

const ::std::string&
RoboCompAGMCommonBehavior::AGMCommonBehavior::ice_id(const ::Ice::Current&) const
{
    return __RoboCompAGMCommonBehavior__AGMCommonBehavior_ids[1];
}

const ::std::string&
RoboCompAGMCommonBehavior::AGMCommonBehavior::ice_staticId()
{
    return __RoboCompAGMCommonBehavior__AGMCommonBehavior_ids[1];
}

::Ice::DispatchStatus
RoboCompAGMCommonBehavior::AGMCommonBehavior::___activateAgent(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::RoboCompAGMCommonBehavior::ParameterMap prs;
    __is->read(prs);
    __inS.endReadParams();
    bool __ret = activateAgent(prs, __current);
    ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
    __os->write(__ret);
    __inS.__endWriteParams(true);
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
RoboCompAGMCommonBehavior::AGMCommonBehavior::___deactivateAgent(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    __inS.readEmptyParams();
    bool __ret = deactivateAgent(__current);
    ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
    __os->write(__ret);
    __inS.__endWriteParams(true);
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
RoboCompAGMCommonBehavior::AGMCommonBehavior::___getAgentState(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    __inS.readEmptyParams();
    ::RoboCompAGMCommonBehavior::StateStruct __ret = getAgentState(__current);
    ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
    __os->write(__ret);
    __inS.__endWriteParams(true);
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
RoboCompAGMCommonBehavior::AGMCommonBehavior::___getAgentParameters(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    __inS.readEmptyParams();
    ::RoboCompAGMCommonBehavior::ParameterMap __ret = getAgentParameters(__current);
    ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
    __os->write(__ret);
    __inS.__endWriteParams(true);
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
RoboCompAGMCommonBehavior::AGMCommonBehavior::___setAgentParameters(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::RoboCompAGMCommonBehavior::ParameterMap prs;
    __is->read(prs);
    __inS.endReadParams();
    bool __ret = setAgentParameters(prs, __current);
    ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
    __os->write(__ret);
    __inS.__endWriteParams(true);
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
RoboCompAGMCommonBehavior::AGMCommonBehavior::___killAgent(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    __inS.readEmptyParams();
    killAgent(__current);
    __inS.__writeEmptyParams();
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
RoboCompAGMCommonBehavior::AGMCommonBehavior::___uptimeAgent(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    __inS.readEmptyParams();
    ::Ice::Int __ret = uptimeAgent(__current);
    ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
    __os->write(__ret);
    __inS.__endWriteParams(true);
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
RoboCompAGMCommonBehavior::AGMCommonBehavior::___reloadConfigAgent(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    __inS.readEmptyParams();
    bool __ret = reloadConfigAgent(__current);
    ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
    __os->write(__ret);
    __inS.__endWriteParams(true);
    return ::Ice::DispatchOK;
}

namespace
{
const ::std::string __RoboCompAGMCommonBehavior__AGMCommonBehavior_all[] =
{
    "activateAgent",
    "deactivateAgent",
    "getAgentParameters",
    "getAgentState",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "killAgent",
    "reloadConfigAgent",
    "setAgentParameters",
    "uptimeAgent"
};

}

::Ice::DispatchStatus
RoboCompAGMCommonBehavior::AGMCommonBehavior::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__RoboCompAGMCommonBehavior__AGMCommonBehavior_all, __RoboCompAGMCommonBehavior__AGMCommonBehavior_all + 12, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __RoboCompAGMCommonBehavior__AGMCommonBehavior_all)
    {
        case 0:
        {
            return ___activateAgent(in, current);
        }
        case 1:
        {
            return ___deactivateAgent(in, current);
        }
        case 2:
        {
            return ___getAgentParameters(in, current);
        }
        case 3:
        {
            return ___getAgentState(in, current);
        }
        case 4:
        {
            return ___ice_id(in, current);
        }
        case 5:
        {
            return ___ice_ids(in, current);
        }
        case 6:
        {
            return ___ice_isA(in, current);
        }
        case 7:
        {
            return ___ice_ping(in, current);
        }
        case 8:
        {
            return ___killAgent(in, current);
        }
        case 9:
        {
            return ___reloadConfigAgent(in, current);
        }
        case 10:
        {
            return ___setAgentParameters(in, current);
        }
        case 11:
        {
            return ___uptimeAgent(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
RoboCompAGMCommonBehavior::AGMCommonBehavior::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
RoboCompAGMCommonBehavior::AGMCommonBehavior::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
RoboCompAGMCommonBehavior::__patch(AGMCommonBehaviorPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::RoboCompAGMCommonBehavior::AGMCommonBehaviorPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::RoboCompAGMCommonBehavior::AGMCommonBehavior::ice_staticId(), v);
    }
}
