// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `AGMAgent.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <AGMAgent.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/BasicStream.h>
#include <Ice/Object.h>
#include <IceUtil/Iterator.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace
{

const ::std::string __RoboCompAGMAgent__AGMAgentTopic__structuralChange_name = "structuralChange";

const ::std::string __RoboCompAGMAgent__AGMAgentTopic__symbolUpdated_name = "symbolUpdated";

const ::std::string __RoboCompAGMAgent__AGMAgentTopic__edgeUpdated_name = "edgeUpdated";

const ::std::string __RoboCompAGMAgent__AGMAgentTopic__edgesUpdated_name = "edgesUpdated";

}
::IceProxy::Ice::Object* ::IceProxy::RoboCompAGMAgent::upCast(::IceProxy::RoboCompAGMAgent::AGMAgentTopic* p) { return p; }

void
::IceProxy::RoboCompAGMAgent::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::RoboCompAGMAgent::AGMAgentTopic>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::RoboCompAGMAgent::AGMAgentTopic;
        v->__copyFrom(proxy);
    }
}

void
IceProxy::RoboCompAGMAgent::AGMAgentTopic::structuralChange(const ::RoboCompAGMWorldModel::Event& modification, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __RoboCompAGMAgent__AGMAgentTopic__structuralChange_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __delBase = __getDelegate(false);
            ::IceDelegate::RoboCompAGMAgent::AGMAgentTopic* __del = dynamic_cast< ::IceDelegate::RoboCompAGMAgent::AGMAgentTopic*>(__delBase.get());
            __del->structuralChange(modification, __ctx, __observer);
            return;
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::RoboCompAGMAgent::AGMAgentTopic::begin_structuralChange(const ::RoboCompAGMWorldModel::Event& modification, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RoboCompAGMAgent__AGMAgentTopic__structuralChange_name, __del, __cookie);
    try
    {
        __result->__prepare(__RoboCompAGMAgent__AGMAgentTopic__structuralChange_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(modification);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

void
IceProxy::RoboCompAGMAgent::AGMAgentTopic::end_structuralChange(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __RoboCompAGMAgent__AGMAgentTopic__structuralChange_name);
}

void
IceProxy::RoboCompAGMAgent::AGMAgentTopic::symbolUpdated(const ::RoboCompAGMWorldModel::Node& nodeModification, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __RoboCompAGMAgent__AGMAgentTopic__symbolUpdated_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __delBase = __getDelegate(false);
            ::IceDelegate::RoboCompAGMAgent::AGMAgentTopic* __del = dynamic_cast< ::IceDelegate::RoboCompAGMAgent::AGMAgentTopic*>(__delBase.get());
            __del->symbolUpdated(nodeModification, __ctx, __observer);
            return;
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::RoboCompAGMAgent::AGMAgentTopic::begin_symbolUpdated(const ::RoboCompAGMWorldModel::Node& nodeModification, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RoboCompAGMAgent__AGMAgentTopic__symbolUpdated_name, __del, __cookie);
    try
    {
        __result->__prepare(__RoboCompAGMAgent__AGMAgentTopic__symbolUpdated_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(nodeModification);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

void
IceProxy::RoboCompAGMAgent::AGMAgentTopic::end_symbolUpdated(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __RoboCompAGMAgent__AGMAgentTopic__symbolUpdated_name);
}

void
IceProxy::RoboCompAGMAgent::AGMAgentTopic::edgeUpdated(const ::RoboCompAGMWorldModel::Edge& edgeModification, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __RoboCompAGMAgent__AGMAgentTopic__edgeUpdated_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __delBase = __getDelegate(false);
            ::IceDelegate::RoboCompAGMAgent::AGMAgentTopic* __del = dynamic_cast< ::IceDelegate::RoboCompAGMAgent::AGMAgentTopic*>(__delBase.get());
            __del->edgeUpdated(edgeModification, __ctx, __observer);
            return;
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::RoboCompAGMAgent::AGMAgentTopic::begin_edgeUpdated(const ::RoboCompAGMWorldModel::Edge& edgeModification, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RoboCompAGMAgent__AGMAgentTopic__edgeUpdated_name, __del, __cookie);
    try
    {
        __result->__prepare(__RoboCompAGMAgent__AGMAgentTopic__edgeUpdated_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(edgeModification);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

void
IceProxy::RoboCompAGMAgent::AGMAgentTopic::end_edgeUpdated(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __RoboCompAGMAgent__AGMAgentTopic__edgeUpdated_name);
}

void
IceProxy::RoboCompAGMAgent::AGMAgentTopic::edgesUpdated(const ::RoboCompAGMWorldModel::EdgeSequence& edgeModifications, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __RoboCompAGMAgent__AGMAgentTopic__edgesUpdated_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __delBase = __getDelegate(false);
            ::IceDelegate::RoboCompAGMAgent::AGMAgentTopic* __del = dynamic_cast< ::IceDelegate::RoboCompAGMAgent::AGMAgentTopic*>(__delBase.get());
            __del->edgesUpdated(edgeModifications, __ctx, __observer);
            return;
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::RoboCompAGMAgent::AGMAgentTopic::begin_edgesUpdated(const ::RoboCompAGMWorldModel::EdgeSequence& edgeModifications, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RoboCompAGMAgent__AGMAgentTopic__edgesUpdated_name, __del, __cookie);
    try
    {
        __result->__prepare(__RoboCompAGMAgent__AGMAgentTopic__edgesUpdated_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(edgeModifications);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

void
IceProxy::RoboCompAGMAgent::AGMAgentTopic::end_edgesUpdated(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __RoboCompAGMAgent__AGMAgentTopic__edgesUpdated_name);
}

const ::std::string&
IceProxy::RoboCompAGMAgent::AGMAgentTopic::ice_staticId()
{
    return ::RoboCompAGMAgent::AGMAgentTopic::ice_staticId();
}

::IceInternal::Handle< ::IceDelegateM::Ice::Object>
IceProxy::RoboCompAGMAgent::AGMAgentTopic::__createDelegateM()
{
    return ::IceInternal::Handle< ::IceDelegateM::Ice::Object>(new ::IceDelegateM::RoboCompAGMAgent::AGMAgentTopic);
}

::IceInternal::Handle< ::IceDelegateD::Ice::Object>
IceProxy::RoboCompAGMAgent::AGMAgentTopic::__createDelegateD()
{
    return ::IceInternal::Handle< ::IceDelegateD::Ice::Object>(new ::IceDelegateD::RoboCompAGMAgent::AGMAgentTopic);
}

::IceProxy::Ice::Object*
IceProxy::RoboCompAGMAgent::AGMAgentTopic::__newInstance() const
{
    return new AGMAgentTopic;
}

void
IceDelegateM::RoboCompAGMAgent::AGMAgentTopic::structuralChange(const ::RoboCompAGMWorldModel::Event& modification, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __RoboCompAGMAgent__AGMAgentTopic__structuralChange_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(modification);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    if(__og.hasResponse())
    {
        try
        {
            if(!__ok)
            {
                try
                {
                    __og.throwUserException();
                }
                catch(const ::Ice::UserException& __ex)
                {
                    ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                    throw __uue;
                }
            }
            __og.readEmptyParams();
        }
        catch(const ::Ice::LocalException& __ex)
        {
            throw ::IceInternal::LocalExceptionWrapper(__ex, false);
        }
    }
}

void
IceDelegateM::RoboCompAGMAgent::AGMAgentTopic::symbolUpdated(const ::RoboCompAGMWorldModel::Node& nodeModification, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __RoboCompAGMAgent__AGMAgentTopic__symbolUpdated_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(nodeModification);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    if(__og.hasResponse())
    {
        try
        {
            if(!__ok)
            {
                try
                {
                    __og.throwUserException();
                }
                catch(const ::Ice::UserException& __ex)
                {
                    ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                    throw __uue;
                }
            }
            __og.readEmptyParams();
        }
        catch(const ::Ice::LocalException& __ex)
        {
            throw ::IceInternal::LocalExceptionWrapper(__ex, false);
        }
    }
}

void
IceDelegateM::RoboCompAGMAgent::AGMAgentTopic::edgeUpdated(const ::RoboCompAGMWorldModel::Edge& edgeModification, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __RoboCompAGMAgent__AGMAgentTopic__edgeUpdated_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(edgeModification);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    if(__og.hasResponse())
    {
        try
        {
            if(!__ok)
            {
                try
                {
                    __og.throwUserException();
                }
                catch(const ::Ice::UserException& __ex)
                {
                    ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                    throw __uue;
                }
            }
            __og.readEmptyParams();
        }
        catch(const ::Ice::LocalException& __ex)
        {
            throw ::IceInternal::LocalExceptionWrapper(__ex, false);
        }
    }
}

void
IceDelegateM::RoboCompAGMAgent::AGMAgentTopic::edgesUpdated(const ::RoboCompAGMWorldModel::EdgeSequence& edgeModifications, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __RoboCompAGMAgent__AGMAgentTopic__edgesUpdated_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(edgeModifications);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    if(__og.hasResponse())
    {
        try
        {
            if(!__ok)
            {
                try
                {
                    __og.throwUserException();
                }
                catch(const ::Ice::UserException& __ex)
                {
                    ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                    throw __uue;
                }
            }
            __og.readEmptyParams();
        }
        catch(const ::Ice::LocalException& __ex)
        {
            throw ::IceInternal::LocalExceptionWrapper(__ex, false);
        }
    }
}

void
IceDelegateD::RoboCompAGMAgent::AGMAgentTopic::structuralChange(const ::RoboCompAGMWorldModel::Event& modification, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(const ::RoboCompAGMWorldModel::Event& __p_modification, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _m_modification(__p_modification)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::RoboCompAGMAgent::AGMAgentTopic* servant = dynamic_cast< ::RoboCompAGMAgent::AGMAgentTopic*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            servant->structuralChange(_m_modification, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        const ::RoboCompAGMWorldModel::Event& _m_modification;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __RoboCompAGMAgent__AGMAgentTopic__structuralChange_name, ::Ice::Normal, __context);
    try
    {
        _DirectI __direct(modification, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
}

void
IceDelegateD::RoboCompAGMAgent::AGMAgentTopic::symbolUpdated(const ::RoboCompAGMWorldModel::Node& nodeModification, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(const ::RoboCompAGMWorldModel::Node& __p_nodeModification, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _m_nodeModification(__p_nodeModification)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::RoboCompAGMAgent::AGMAgentTopic* servant = dynamic_cast< ::RoboCompAGMAgent::AGMAgentTopic*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            servant->symbolUpdated(_m_nodeModification, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        const ::RoboCompAGMWorldModel::Node& _m_nodeModification;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __RoboCompAGMAgent__AGMAgentTopic__symbolUpdated_name, ::Ice::Normal, __context);
    try
    {
        _DirectI __direct(nodeModification, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
}

void
IceDelegateD::RoboCompAGMAgent::AGMAgentTopic::edgeUpdated(const ::RoboCompAGMWorldModel::Edge& edgeModification, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(const ::RoboCompAGMWorldModel::Edge& __p_edgeModification, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _m_edgeModification(__p_edgeModification)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::RoboCompAGMAgent::AGMAgentTopic* servant = dynamic_cast< ::RoboCompAGMAgent::AGMAgentTopic*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            servant->edgeUpdated(_m_edgeModification, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        const ::RoboCompAGMWorldModel::Edge& _m_edgeModification;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __RoboCompAGMAgent__AGMAgentTopic__edgeUpdated_name, ::Ice::Normal, __context);
    try
    {
        _DirectI __direct(edgeModification, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
}

void
IceDelegateD::RoboCompAGMAgent::AGMAgentTopic::edgesUpdated(const ::RoboCompAGMWorldModel::EdgeSequence& edgeModifications, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(const ::RoboCompAGMWorldModel::EdgeSequence& __p_edgeModifications, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _m_edgeModifications(__p_edgeModifications)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::RoboCompAGMAgent::AGMAgentTopic* servant = dynamic_cast< ::RoboCompAGMAgent::AGMAgentTopic*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            servant->edgesUpdated(_m_edgeModifications, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        const ::RoboCompAGMWorldModel::EdgeSequence& _m_edgeModifications;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __RoboCompAGMAgent__AGMAgentTopic__edgesUpdated_name, ::Ice::Normal, __context);
    try
    {
        _DirectI __direct(edgeModifications, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
}

::Ice::Object* RoboCompAGMAgent::upCast(::RoboCompAGMAgent::AGMAgentTopic* p) { return p; }

namespace
{
const ::std::string __RoboCompAGMAgent__AGMAgentTopic_ids[2] =
{
    "::Ice::Object",
    "::RoboCompAGMAgent::AGMAgentTopic"
};

}

bool
RoboCompAGMAgent::AGMAgentTopic::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__RoboCompAGMAgent__AGMAgentTopic_ids, __RoboCompAGMAgent__AGMAgentTopic_ids + 2, _s);
}

::std::vector< ::std::string>
RoboCompAGMAgent::AGMAgentTopic::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__RoboCompAGMAgent__AGMAgentTopic_ids[0], &__RoboCompAGMAgent__AGMAgentTopic_ids[2]);
}

const ::std::string&
RoboCompAGMAgent::AGMAgentTopic::ice_id(const ::Ice::Current&) const
{
    return __RoboCompAGMAgent__AGMAgentTopic_ids[1];
}

const ::std::string&
RoboCompAGMAgent::AGMAgentTopic::ice_staticId()
{
    return __RoboCompAGMAgent__AGMAgentTopic_ids[1];
}

::Ice::DispatchStatus
RoboCompAGMAgent::AGMAgentTopic::___structuralChange(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::RoboCompAGMWorldModel::Event modification;
    __is->read(modification);
    __inS.endReadParams();
    structuralChange(modification, __current);
    __inS.__writeEmptyParams();
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
RoboCompAGMAgent::AGMAgentTopic::___symbolUpdated(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::RoboCompAGMWorldModel::Node nodeModification;
    __is->read(nodeModification);
    __inS.endReadParams();
    symbolUpdated(nodeModification, __current);
    __inS.__writeEmptyParams();
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
RoboCompAGMAgent::AGMAgentTopic::___edgeUpdated(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::RoboCompAGMWorldModel::Edge edgeModification;
    __is->read(edgeModification);
    __inS.endReadParams();
    edgeUpdated(edgeModification, __current);
    __inS.__writeEmptyParams();
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
RoboCompAGMAgent::AGMAgentTopic::___edgesUpdated(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::RoboCompAGMWorldModel::EdgeSequence edgeModifications;
    __is->read(edgeModifications);
    __inS.endReadParams();
    edgesUpdated(edgeModifications, __current);
    __inS.__writeEmptyParams();
    return ::Ice::DispatchOK;
}

namespace
{
const ::std::string __RoboCompAGMAgent__AGMAgentTopic_all[] =
{
    "edgeUpdated",
    "edgesUpdated",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "structuralChange",
    "symbolUpdated"
};

}

::Ice::DispatchStatus
RoboCompAGMAgent::AGMAgentTopic::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__RoboCompAGMAgent__AGMAgentTopic_all, __RoboCompAGMAgent__AGMAgentTopic_all + 8, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __RoboCompAGMAgent__AGMAgentTopic_all)
    {
        case 0:
        {
            return ___edgeUpdated(in, current);
        }
        case 1:
        {
            return ___edgesUpdated(in, current);
        }
        case 2:
        {
            return ___ice_id(in, current);
        }
        case 3:
        {
            return ___ice_ids(in, current);
        }
        case 4:
        {
            return ___ice_isA(in, current);
        }
        case 5:
        {
            return ___ice_ping(in, current);
        }
        case 6:
        {
            return ___structuralChange(in, current);
        }
        case 7:
        {
            return ___symbolUpdated(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
RoboCompAGMAgent::AGMAgentTopic::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
RoboCompAGMAgent::AGMAgentTopic::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
RoboCompAGMAgent::__patch(AGMAgentTopicPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::RoboCompAGMAgent::AGMAgentTopicPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::RoboCompAGMAgent::AGMAgentTopic::ice_staticId(), v);
    }
}
