// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `AGMAgent.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef ____AGMAgent_h__
#define ____AGMAgent_h__

#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/Incoming.h>
#include <Ice/Direct.h>
#include <IceUtil/ScopedArray.h>
#include <IceUtil/Optional.h>
#include <Ice/StreamF.h>
#include <AGMWorldModel.h>
#include <Ice/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace IceProxy
{

namespace RoboCompAGMAgent
{

class AGMAgentTopic;
void __read(::IceInternal::BasicStream*, ::IceInternal::ProxyHandle< ::IceProxy::RoboCompAGMAgent::AGMAgentTopic>&);
::IceProxy::Ice::Object* upCast(::IceProxy::RoboCompAGMAgent::AGMAgentTopic*);

}

}

namespace RoboCompAGMAgent
{

class AGMAgentTopic;
bool operator==(const AGMAgentTopic&, const AGMAgentTopic&);
bool operator<(const AGMAgentTopic&, const AGMAgentTopic&);
::Ice::Object* upCast(::RoboCompAGMAgent::AGMAgentTopic*);
typedef ::IceInternal::Handle< ::RoboCompAGMAgent::AGMAgentTopic> AGMAgentTopicPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::RoboCompAGMAgent::AGMAgentTopic> AGMAgentTopicPrx;
void __patch(AGMAgentTopicPtr&, const ::Ice::ObjectPtr&);

}

namespace RoboCompAGMAgent
{

class Callback_AGMAgentTopic_structuralChange_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_AGMAgentTopic_structuralChange_Base> Callback_AGMAgentTopic_structuralChangePtr;

class Callback_AGMAgentTopic_symbolUpdated_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_AGMAgentTopic_symbolUpdated_Base> Callback_AGMAgentTopic_symbolUpdatedPtr;

class Callback_AGMAgentTopic_edgeUpdated_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_AGMAgentTopic_edgeUpdated_Base> Callback_AGMAgentTopic_edgeUpdatedPtr;

class Callback_AGMAgentTopic_edgesUpdated_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_AGMAgentTopic_edgesUpdated_Base> Callback_AGMAgentTopic_edgesUpdatedPtr;

}

namespace IceProxy
{

namespace RoboCompAGMAgent
{

class AGMAgentTopic : virtual public ::IceProxy::Ice::Object
{
public:

    void structuralChange(const ::RoboCompAGMWorldModel::Event& modification)
    {
        structuralChange(modification, 0);
    }
    void structuralChange(const ::RoboCompAGMWorldModel::Event& modification, const ::Ice::Context& __ctx)
    {
        structuralChange(modification, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_structuralChange(const ::RoboCompAGMWorldModel::Event& modification, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_structuralChange(modification, 0, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent));
    }
    ::Ice::AsyncResultPtr
    begin_structuralChange(const ::RoboCompAGMWorldModel::Event& modification, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_structuralChange(modification, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_structuralChange(const ::RoboCompAGMWorldModel::Event& modification, const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_structuralChange(modification, &__ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_structuralChange(const ::RoboCompAGMWorldModel::Event& modification, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_structuralChange(modification, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_structuralChange(const ::RoboCompAGMWorldModel::Event& modification)
    {
        return begin_structuralChange(modification, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_structuralChange(const ::RoboCompAGMWorldModel::Event& modification, const ::Ice::Context& __ctx)
    {
        return begin_structuralChange(modification, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_structuralChange(const ::RoboCompAGMWorldModel::Event& modification, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_structuralChange(modification, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_structuralChange(const ::RoboCompAGMWorldModel::Event& modification, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_structuralChange(modification, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_structuralChange(const ::RoboCompAGMWorldModel::Event& modification, const ::RoboCompAGMAgent::Callback_AGMAgentTopic_structuralChangePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_structuralChange(modification, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_structuralChange(const ::RoboCompAGMWorldModel::Event& modification, const ::Ice::Context& __ctx, const ::RoboCompAGMAgent::Callback_AGMAgentTopic_structuralChangePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_structuralChange(modification, &__ctx, __del, __cookie);
    }

    void end_structuralChange(const ::Ice::AsyncResultPtr&);
    
private:

    void structuralChange(const ::RoboCompAGMWorldModel::Event&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_structuralChange(const ::RoboCompAGMWorldModel::Event&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void symbolUpdated(const ::RoboCompAGMWorldModel::Node& nodeModification)
    {
        symbolUpdated(nodeModification, 0);
    }
    void symbolUpdated(const ::RoboCompAGMWorldModel::Node& nodeModification, const ::Ice::Context& __ctx)
    {
        symbolUpdated(nodeModification, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_symbolUpdated(const ::RoboCompAGMWorldModel::Node& nodeModification, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_symbolUpdated(nodeModification, 0, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent));
    }
    ::Ice::AsyncResultPtr
    begin_symbolUpdated(const ::RoboCompAGMWorldModel::Node& nodeModification, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_symbolUpdated(nodeModification, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_symbolUpdated(const ::RoboCompAGMWorldModel::Node& nodeModification, const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_symbolUpdated(nodeModification, &__ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_symbolUpdated(const ::RoboCompAGMWorldModel::Node& nodeModification, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_symbolUpdated(nodeModification, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_symbolUpdated(const ::RoboCompAGMWorldModel::Node& nodeModification)
    {
        return begin_symbolUpdated(nodeModification, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_symbolUpdated(const ::RoboCompAGMWorldModel::Node& nodeModification, const ::Ice::Context& __ctx)
    {
        return begin_symbolUpdated(nodeModification, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_symbolUpdated(const ::RoboCompAGMWorldModel::Node& nodeModification, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_symbolUpdated(nodeModification, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_symbolUpdated(const ::RoboCompAGMWorldModel::Node& nodeModification, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_symbolUpdated(nodeModification, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_symbolUpdated(const ::RoboCompAGMWorldModel::Node& nodeModification, const ::RoboCompAGMAgent::Callback_AGMAgentTopic_symbolUpdatedPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_symbolUpdated(nodeModification, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_symbolUpdated(const ::RoboCompAGMWorldModel::Node& nodeModification, const ::Ice::Context& __ctx, const ::RoboCompAGMAgent::Callback_AGMAgentTopic_symbolUpdatedPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_symbolUpdated(nodeModification, &__ctx, __del, __cookie);
    }

    void end_symbolUpdated(const ::Ice::AsyncResultPtr&);
    
private:

    void symbolUpdated(const ::RoboCompAGMWorldModel::Node&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_symbolUpdated(const ::RoboCompAGMWorldModel::Node&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void edgeUpdated(const ::RoboCompAGMWorldModel::Edge& edgeModification)
    {
        edgeUpdated(edgeModification, 0);
    }
    void edgeUpdated(const ::RoboCompAGMWorldModel::Edge& edgeModification, const ::Ice::Context& __ctx)
    {
        edgeUpdated(edgeModification, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_edgeUpdated(const ::RoboCompAGMWorldModel::Edge& edgeModification, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_edgeUpdated(edgeModification, 0, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent));
    }
    ::Ice::AsyncResultPtr
    begin_edgeUpdated(const ::RoboCompAGMWorldModel::Edge& edgeModification, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_edgeUpdated(edgeModification, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_edgeUpdated(const ::RoboCompAGMWorldModel::Edge& edgeModification, const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_edgeUpdated(edgeModification, &__ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_edgeUpdated(const ::RoboCompAGMWorldModel::Edge& edgeModification, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_edgeUpdated(edgeModification, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_edgeUpdated(const ::RoboCompAGMWorldModel::Edge& edgeModification)
    {
        return begin_edgeUpdated(edgeModification, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_edgeUpdated(const ::RoboCompAGMWorldModel::Edge& edgeModification, const ::Ice::Context& __ctx)
    {
        return begin_edgeUpdated(edgeModification, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_edgeUpdated(const ::RoboCompAGMWorldModel::Edge& edgeModification, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_edgeUpdated(edgeModification, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_edgeUpdated(const ::RoboCompAGMWorldModel::Edge& edgeModification, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_edgeUpdated(edgeModification, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_edgeUpdated(const ::RoboCompAGMWorldModel::Edge& edgeModification, const ::RoboCompAGMAgent::Callback_AGMAgentTopic_edgeUpdatedPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_edgeUpdated(edgeModification, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_edgeUpdated(const ::RoboCompAGMWorldModel::Edge& edgeModification, const ::Ice::Context& __ctx, const ::RoboCompAGMAgent::Callback_AGMAgentTopic_edgeUpdatedPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_edgeUpdated(edgeModification, &__ctx, __del, __cookie);
    }

    void end_edgeUpdated(const ::Ice::AsyncResultPtr&);
    
private:

    void edgeUpdated(const ::RoboCompAGMWorldModel::Edge&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_edgeUpdated(const ::RoboCompAGMWorldModel::Edge&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void edgesUpdated(const ::RoboCompAGMWorldModel::EdgeSequence& edgeModifications)
    {
        edgesUpdated(edgeModifications, 0);
    }
    void edgesUpdated(const ::RoboCompAGMWorldModel::EdgeSequence& edgeModifications, const ::Ice::Context& __ctx)
    {
        edgesUpdated(edgeModifications, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_edgesUpdated(const ::RoboCompAGMWorldModel::EdgeSequence& edgeModifications, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_edgesUpdated(edgeModifications, 0, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent));
    }
    ::Ice::AsyncResultPtr
    begin_edgesUpdated(const ::RoboCompAGMWorldModel::EdgeSequence& edgeModifications, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_edgesUpdated(edgeModifications, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_edgesUpdated(const ::RoboCompAGMWorldModel::EdgeSequence& edgeModifications, const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_edgesUpdated(edgeModifications, &__ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_edgesUpdated(const ::RoboCompAGMWorldModel::EdgeSequence& edgeModifications, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_edgesUpdated(edgeModifications, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_edgesUpdated(const ::RoboCompAGMWorldModel::EdgeSequence& edgeModifications)
    {
        return begin_edgesUpdated(edgeModifications, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_edgesUpdated(const ::RoboCompAGMWorldModel::EdgeSequence& edgeModifications, const ::Ice::Context& __ctx)
    {
        return begin_edgesUpdated(edgeModifications, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_edgesUpdated(const ::RoboCompAGMWorldModel::EdgeSequence& edgeModifications, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_edgesUpdated(edgeModifications, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_edgesUpdated(const ::RoboCompAGMWorldModel::EdgeSequence& edgeModifications, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_edgesUpdated(edgeModifications, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_edgesUpdated(const ::RoboCompAGMWorldModel::EdgeSequence& edgeModifications, const ::RoboCompAGMAgent::Callback_AGMAgentTopic_edgesUpdatedPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_edgesUpdated(edgeModifications, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_edgesUpdated(const ::RoboCompAGMWorldModel::EdgeSequence& edgeModifications, const ::Ice::Context& __ctx, const ::RoboCompAGMAgent::Callback_AGMAgentTopic_edgesUpdatedPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_edgesUpdated(edgeModifications, &__ctx, __del, __cookie);
    }

    void end_edgesUpdated(const ::Ice::AsyncResultPtr&);
    
private:

    void edgesUpdated(const ::RoboCompAGMWorldModel::EdgeSequence&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_edgesUpdated(const ::RoboCompAGMWorldModel::EdgeSequence&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<AGMAgentTopic> ice_context(const ::Ice::Context& __context) const
    {
        return dynamic_cast<AGMAgentTopic*>(::IceProxy::Ice::Object::ice_context(__context).get());
    }
    
    ::IceInternal::ProxyHandle<AGMAgentTopic> ice_adapterId(const ::std::string& __id) const
    {
        return dynamic_cast<AGMAgentTopic*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<AGMAgentTopic> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return dynamic_cast<AGMAgentTopic*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    }
    
    ::IceInternal::ProxyHandle<AGMAgentTopic> ice_locatorCacheTimeout(int __timeout) const
    {
        return dynamic_cast<AGMAgentTopic*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<AGMAgentTopic> ice_connectionCached(bool __cached) const
    {
        return dynamic_cast<AGMAgentTopic*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    }
    
    ::IceInternal::ProxyHandle<AGMAgentTopic> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return dynamic_cast<AGMAgentTopic*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    }
    
    ::IceInternal::ProxyHandle<AGMAgentTopic> ice_secure(bool __secure) const
    {
        return dynamic_cast<AGMAgentTopic*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    }
    
    ::IceInternal::ProxyHandle<AGMAgentTopic> ice_preferSecure(bool __preferSecure) const
    {
        return dynamic_cast<AGMAgentTopic*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    }
    
    ::IceInternal::ProxyHandle<AGMAgentTopic> ice_router(const ::Ice::RouterPrx& __router) const
    {
        return dynamic_cast<AGMAgentTopic*>(::IceProxy::Ice::Object::ice_router(__router).get());
    }
    
    ::IceInternal::ProxyHandle<AGMAgentTopic> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
        return dynamic_cast<AGMAgentTopic*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    }
    
    ::IceInternal::ProxyHandle<AGMAgentTopic> ice_collocationOptimized(bool __co) const
    {
        return dynamic_cast<AGMAgentTopic*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    }
    
    ::IceInternal::ProxyHandle<AGMAgentTopic> ice_twoway() const
    {
        return dynamic_cast<AGMAgentTopic*>(::IceProxy::Ice::Object::ice_twoway().get());
    }
    
    ::IceInternal::ProxyHandle<AGMAgentTopic> ice_oneway() const
    {
        return dynamic_cast<AGMAgentTopic*>(::IceProxy::Ice::Object::ice_oneway().get());
    }
    
    ::IceInternal::ProxyHandle<AGMAgentTopic> ice_batchOneway() const
    {
        return dynamic_cast<AGMAgentTopic*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    }
    
    ::IceInternal::ProxyHandle<AGMAgentTopic> ice_datagram() const
    {
        return dynamic_cast<AGMAgentTopic*>(::IceProxy::Ice::Object::ice_datagram().get());
    }
    
    ::IceInternal::ProxyHandle<AGMAgentTopic> ice_batchDatagram() const
    {
        return dynamic_cast<AGMAgentTopic*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    }
    
    ::IceInternal::ProxyHandle<AGMAgentTopic> ice_compress(bool __compress) const
    {
        return dynamic_cast<AGMAgentTopic*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    }
    
    ::IceInternal::ProxyHandle<AGMAgentTopic> ice_timeout(int __timeout) const
    {
        return dynamic_cast<AGMAgentTopic*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<AGMAgentTopic> ice_connectionId(const ::std::string& __id) const
    {
        return dynamic_cast<AGMAgentTopic*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<AGMAgentTopic> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return dynamic_cast<AGMAgentTopic*>(::IceProxy::Ice::Object::ice_encodingVersion(__v).get());
    }
    
    static const ::std::string& ice_staticId();

private: 

    virtual ::IceInternal::Handle< ::IceDelegateM::Ice::Object> __createDelegateM();
    virtual ::IceInternal::Handle< ::IceDelegateD::Ice::Object> __createDelegateD();
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

namespace IceDelegate
{

namespace RoboCompAGMAgent
{

class AGMAgentTopic : virtual public ::IceDelegate::Ice::Object
{
public:

    virtual void structuralChange(const ::RoboCompAGMWorldModel::Event&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual void symbolUpdated(const ::RoboCompAGMWorldModel::Node&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual void edgeUpdated(const ::RoboCompAGMWorldModel::Edge&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual void edgesUpdated(const ::RoboCompAGMWorldModel::EdgeSequence&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;
};

}

}

namespace IceDelegateM
{

namespace RoboCompAGMAgent
{

class AGMAgentTopic : virtual public ::IceDelegate::RoboCompAGMAgent::AGMAgentTopic,
                      virtual public ::IceDelegateM::Ice::Object
{
public:

    virtual void structuralChange(const ::RoboCompAGMWorldModel::Event&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void symbolUpdated(const ::RoboCompAGMWorldModel::Node&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void edgeUpdated(const ::RoboCompAGMWorldModel::Edge&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void edgesUpdated(const ::RoboCompAGMWorldModel::EdgeSequence&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace IceDelegateD
{

namespace RoboCompAGMAgent
{

class AGMAgentTopic : virtual public ::IceDelegate::RoboCompAGMAgent::AGMAgentTopic,
                      virtual public ::IceDelegateD::Ice::Object
{
public:

    virtual void structuralChange(const ::RoboCompAGMWorldModel::Event&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void symbolUpdated(const ::RoboCompAGMWorldModel::Node&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void edgeUpdated(const ::RoboCompAGMWorldModel::Edge&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void edgesUpdated(const ::RoboCompAGMWorldModel::EdgeSequence&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace RoboCompAGMAgent
{

class AGMAgentTopic : virtual public ::Ice::Object
{
public:

    typedef AGMAgentTopicPrx ProxyType;
    typedef AGMAgentTopicPtr PointerType;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual void structuralChange(const ::RoboCompAGMWorldModel::Event&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___structuralChange(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void symbolUpdated(const ::RoboCompAGMWorldModel::Node&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___symbolUpdated(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void edgeUpdated(const ::RoboCompAGMWorldModel::Edge&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___edgeUpdated(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void edgesUpdated(const ::RoboCompAGMWorldModel::EdgeSequence&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___edgesUpdated(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    #ifdef __SUNPRO_CC
    using ::Ice::Object::__writeImpl;
    using ::Ice::Object::__readImpl;
    #endif
};

inline bool operator==(const AGMAgentTopic& l, const AGMAgentTopic& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const AGMAgentTopic& l, const AGMAgentTopic& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

namespace RoboCompAGMAgent
{

template<class T>
class CallbackNC_AGMAgentTopic_structuralChange : public Callback_AGMAgentTopic_structuralChange_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_AGMAgentTopic_structuralChange(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_AGMAgentTopic_structuralChangePtr
newCallback_AGMAgentTopic_structuralChange(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AGMAgentTopic_structuralChange<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_AGMAgentTopic_structuralChangePtr
newCallback_AGMAgentTopic_structuralChange(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AGMAgentTopic_structuralChange<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_AGMAgentTopic_structuralChangePtr
newCallback_AGMAgentTopic_structuralChange(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AGMAgentTopic_structuralChange<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_AGMAgentTopic_structuralChangePtr
newCallback_AGMAgentTopic_structuralChange(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AGMAgentTopic_structuralChange<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_AGMAgentTopic_structuralChange : public Callback_AGMAgentTopic_structuralChange_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_AGMAgentTopic_structuralChange(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_AGMAgentTopic_structuralChangePtr
newCallback_AGMAgentTopic_structuralChange(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AGMAgentTopic_structuralChange<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_AGMAgentTopic_structuralChangePtr
newCallback_AGMAgentTopic_structuralChange(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AGMAgentTopic_structuralChange<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_AGMAgentTopic_structuralChangePtr
newCallback_AGMAgentTopic_structuralChange(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AGMAgentTopic_structuralChange<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_AGMAgentTopic_structuralChangePtr
newCallback_AGMAgentTopic_structuralChange(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AGMAgentTopic_structuralChange<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_AGMAgentTopic_symbolUpdated : public Callback_AGMAgentTopic_symbolUpdated_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_AGMAgentTopic_symbolUpdated(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_AGMAgentTopic_symbolUpdatedPtr
newCallback_AGMAgentTopic_symbolUpdated(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AGMAgentTopic_symbolUpdated<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_AGMAgentTopic_symbolUpdatedPtr
newCallback_AGMAgentTopic_symbolUpdated(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AGMAgentTopic_symbolUpdated<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_AGMAgentTopic_symbolUpdatedPtr
newCallback_AGMAgentTopic_symbolUpdated(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AGMAgentTopic_symbolUpdated<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_AGMAgentTopic_symbolUpdatedPtr
newCallback_AGMAgentTopic_symbolUpdated(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AGMAgentTopic_symbolUpdated<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_AGMAgentTopic_symbolUpdated : public Callback_AGMAgentTopic_symbolUpdated_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_AGMAgentTopic_symbolUpdated(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_AGMAgentTopic_symbolUpdatedPtr
newCallback_AGMAgentTopic_symbolUpdated(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AGMAgentTopic_symbolUpdated<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_AGMAgentTopic_symbolUpdatedPtr
newCallback_AGMAgentTopic_symbolUpdated(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AGMAgentTopic_symbolUpdated<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_AGMAgentTopic_symbolUpdatedPtr
newCallback_AGMAgentTopic_symbolUpdated(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AGMAgentTopic_symbolUpdated<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_AGMAgentTopic_symbolUpdatedPtr
newCallback_AGMAgentTopic_symbolUpdated(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AGMAgentTopic_symbolUpdated<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_AGMAgentTopic_edgeUpdated : public Callback_AGMAgentTopic_edgeUpdated_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_AGMAgentTopic_edgeUpdated(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_AGMAgentTopic_edgeUpdatedPtr
newCallback_AGMAgentTopic_edgeUpdated(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AGMAgentTopic_edgeUpdated<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_AGMAgentTopic_edgeUpdatedPtr
newCallback_AGMAgentTopic_edgeUpdated(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AGMAgentTopic_edgeUpdated<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_AGMAgentTopic_edgeUpdatedPtr
newCallback_AGMAgentTopic_edgeUpdated(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AGMAgentTopic_edgeUpdated<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_AGMAgentTopic_edgeUpdatedPtr
newCallback_AGMAgentTopic_edgeUpdated(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AGMAgentTopic_edgeUpdated<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_AGMAgentTopic_edgeUpdated : public Callback_AGMAgentTopic_edgeUpdated_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_AGMAgentTopic_edgeUpdated(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_AGMAgentTopic_edgeUpdatedPtr
newCallback_AGMAgentTopic_edgeUpdated(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AGMAgentTopic_edgeUpdated<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_AGMAgentTopic_edgeUpdatedPtr
newCallback_AGMAgentTopic_edgeUpdated(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AGMAgentTopic_edgeUpdated<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_AGMAgentTopic_edgeUpdatedPtr
newCallback_AGMAgentTopic_edgeUpdated(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AGMAgentTopic_edgeUpdated<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_AGMAgentTopic_edgeUpdatedPtr
newCallback_AGMAgentTopic_edgeUpdated(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AGMAgentTopic_edgeUpdated<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_AGMAgentTopic_edgesUpdated : public Callback_AGMAgentTopic_edgesUpdated_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_AGMAgentTopic_edgesUpdated(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_AGMAgentTopic_edgesUpdatedPtr
newCallback_AGMAgentTopic_edgesUpdated(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AGMAgentTopic_edgesUpdated<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_AGMAgentTopic_edgesUpdatedPtr
newCallback_AGMAgentTopic_edgesUpdated(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AGMAgentTopic_edgesUpdated<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_AGMAgentTopic_edgesUpdatedPtr
newCallback_AGMAgentTopic_edgesUpdated(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AGMAgentTopic_edgesUpdated<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_AGMAgentTopic_edgesUpdatedPtr
newCallback_AGMAgentTopic_edgesUpdated(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_AGMAgentTopic_edgesUpdated<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_AGMAgentTopic_edgesUpdated : public Callback_AGMAgentTopic_edgesUpdated_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_AGMAgentTopic_edgesUpdated(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_AGMAgentTopic_edgesUpdatedPtr
newCallback_AGMAgentTopic_edgesUpdated(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AGMAgentTopic_edgesUpdated<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_AGMAgentTopic_edgesUpdatedPtr
newCallback_AGMAgentTopic_edgesUpdated(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AGMAgentTopic_edgesUpdated<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_AGMAgentTopic_edgesUpdatedPtr
newCallback_AGMAgentTopic_edgesUpdated(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AGMAgentTopic_edgesUpdated<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_AGMAgentTopic_edgesUpdatedPtr
newCallback_AGMAgentTopic_edgesUpdated(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_AGMAgentTopic_edgesUpdated<T, CT>(instance, 0, excb, sentcb);
}

}

#endif
