// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `PeopleDetection.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef ____PeopleDetection_h__
#define ____PeopleDetection_h__

#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/Incoming.h>
#include <Ice/Direct.h>
#include <IceUtil/ScopedArray.h>
#include <IceUtil/Optional.h>
#include <Ice/StreamF.h>
#include <Ice/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace IceProxy
{

namespace RoboCompPeopleDetection
{

class PeopleDetection;
void __read(::IceInternal::BasicStream*, ::IceInternal::ProxyHandle< ::IceProxy::RoboCompPeopleDetection::PeopleDetection>&);
::IceProxy::Ice::Object* upCast(::IceProxy::RoboCompPeopleDetection::PeopleDetection*);

}

}

namespace RoboCompPeopleDetection
{

class PeopleDetection;
bool operator==(const PeopleDetection&, const PeopleDetection&);
bool operator<(const PeopleDetection&, const PeopleDetection&);
::Ice::Object* upCast(::RoboCompPeopleDetection::PeopleDetection*);
typedef ::IceInternal::Handle< ::RoboCompPeopleDetection::PeopleDetection> PeopleDetectionPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::RoboCompPeopleDetection::PeopleDetection> PeopleDetectionPrx;
void __patch(PeopleDetectionPtr&, const ::Ice::ObjectPtr&);

}

namespace RoboCompPeopleDetection
{

class Callback_PeopleDetection_peopleDetected_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_PeopleDetection_peopleDetected_Base> Callback_PeopleDetection_peopleDetectedPtr;

}

namespace IceProxy
{

namespace RoboCompPeopleDetection
{

class PeopleDetection : virtual public ::IceProxy::Ice::Object
{
public:

    void peopleDetected(bool people)
    {
        peopleDetected(people, 0);
    }
    void peopleDetected(bool people, const ::Ice::Context& __ctx)
    {
        peopleDetected(people, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_peopleDetected(bool people, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_peopleDetected(people, 0, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent));
    }
    ::Ice::AsyncResultPtr
    begin_peopleDetected(bool people, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_peopleDetected(people, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_peopleDetected(bool people, const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_peopleDetected(people, &__ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_peopleDetected(bool people, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_peopleDetected(people, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_peopleDetected(bool people)
    {
        return begin_peopleDetected(people, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_peopleDetected(bool people, const ::Ice::Context& __ctx)
    {
        return begin_peopleDetected(people, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_peopleDetected(bool people, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_peopleDetected(people, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_peopleDetected(bool people, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_peopleDetected(people, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_peopleDetected(bool people, const ::RoboCompPeopleDetection::Callback_PeopleDetection_peopleDetectedPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_peopleDetected(people, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_peopleDetected(bool people, const ::Ice::Context& __ctx, const ::RoboCompPeopleDetection::Callback_PeopleDetection_peopleDetectedPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_peopleDetected(people, &__ctx, __del, __cookie);
    }

    void end_peopleDetected(const ::Ice::AsyncResultPtr&);
    
private:

    void peopleDetected(bool, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_peopleDetected(bool, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<PeopleDetection> ice_context(const ::Ice::Context& __context) const
    {
        return dynamic_cast<PeopleDetection*>(::IceProxy::Ice::Object::ice_context(__context).get());
    }
    
    ::IceInternal::ProxyHandle<PeopleDetection> ice_adapterId(const ::std::string& __id) const
    {
        return dynamic_cast<PeopleDetection*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<PeopleDetection> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return dynamic_cast<PeopleDetection*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    }
    
    ::IceInternal::ProxyHandle<PeopleDetection> ice_locatorCacheTimeout(int __timeout) const
    {
        return dynamic_cast<PeopleDetection*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<PeopleDetection> ice_connectionCached(bool __cached) const
    {
        return dynamic_cast<PeopleDetection*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    }
    
    ::IceInternal::ProxyHandle<PeopleDetection> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return dynamic_cast<PeopleDetection*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    }
    
    ::IceInternal::ProxyHandle<PeopleDetection> ice_secure(bool __secure) const
    {
        return dynamic_cast<PeopleDetection*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    }
    
    ::IceInternal::ProxyHandle<PeopleDetection> ice_preferSecure(bool __preferSecure) const
    {
        return dynamic_cast<PeopleDetection*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    }
    
    ::IceInternal::ProxyHandle<PeopleDetection> ice_router(const ::Ice::RouterPrx& __router) const
    {
        return dynamic_cast<PeopleDetection*>(::IceProxy::Ice::Object::ice_router(__router).get());
    }
    
    ::IceInternal::ProxyHandle<PeopleDetection> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
        return dynamic_cast<PeopleDetection*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    }
    
    ::IceInternal::ProxyHandle<PeopleDetection> ice_collocationOptimized(bool __co) const
    {
        return dynamic_cast<PeopleDetection*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    }
    
    ::IceInternal::ProxyHandle<PeopleDetection> ice_twoway() const
    {
        return dynamic_cast<PeopleDetection*>(::IceProxy::Ice::Object::ice_twoway().get());
    }
    
    ::IceInternal::ProxyHandle<PeopleDetection> ice_oneway() const
    {
        return dynamic_cast<PeopleDetection*>(::IceProxy::Ice::Object::ice_oneway().get());
    }
    
    ::IceInternal::ProxyHandle<PeopleDetection> ice_batchOneway() const
    {
        return dynamic_cast<PeopleDetection*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    }
    
    ::IceInternal::ProxyHandle<PeopleDetection> ice_datagram() const
    {
        return dynamic_cast<PeopleDetection*>(::IceProxy::Ice::Object::ice_datagram().get());
    }
    
    ::IceInternal::ProxyHandle<PeopleDetection> ice_batchDatagram() const
    {
        return dynamic_cast<PeopleDetection*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    }
    
    ::IceInternal::ProxyHandle<PeopleDetection> ice_compress(bool __compress) const
    {
        return dynamic_cast<PeopleDetection*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    }
    
    ::IceInternal::ProxyHandle<PeopleDetection> ice_timeout(int __timeout) const
    {
        return dynamic_cast<PeopleDetection*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<PeopleDetection> ice_connectionId(const ::std::string& __id) const
    {
        return dynamic_cast<PeopleDetection*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<PeopleDetection> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return dynamic_cast<PeopleDetection*>(::IceProxy::Ice::Object::ice_encodingVersion(__v).get());
    }
    
    static const ::std::string& ice_staticId();

private: 

    virtual ::IceInternal::Handle< ::IceDelegateM::Ice::Object> __createDelegateM();
    virtual ::IceInternal::Handle< ::IceDelegateD::Ice::Object> __createDelegateD();
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

namespace IceDelegate
{

namespace RoboCompPeopleDetection
{

class PeopleDetection : virtual public ::IceDelegate::Ice::Object
{
public:

    virtual void peopleDetected(bool, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;
};

}

}

namespace IceDelegateM
{

namespace RoboCompPeopleDetection
{

class PeopleDetection : virtual public ::IceDelegate::RoboCompPeopleDetection::PeopleDetection,
                        virtual public ::IceDelegateM::Ice::Object
{
public:

    virtual void peopleDetected(bool, const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace IceDelegateD
{

namespace RoboCompPeopleDetection
{

class PeopleDetection : virtual public ::IceDelegate::RoboCompPeopleDetection::PeopleDetection,
                        virtual public ::IceDelegateD::Ice::Object
{
public:

    virtual void peopleDetected(bool, const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace RoboCompPeopleDetection
{

class PeopleDetection : virtual public ::Ice::Object
{
public:

    typedef PeopleDetectionPrx ProxyType;
    typedef PeopleDetectionPtr PointerType;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual void peopleDetected(bool, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___peopleDetected(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    #ifdef __SUNPRO_CC
    using ::Ice::Object::__writeImpl;
    using ::Ice::Object::__readImpl;
    #endif
};

inline bool operator==(const PeopleDetection& l, const PeopleDetection& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const PeopleDetection& l, const PeopleDetection& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

namespace RoboCompPeopleDetection
{

template<class T>
class CallbackNC_PeopleDetection_peopleDetected : public Callback_PeopleDetection_peopleDetected_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_PeopleDetection_peopleDetected(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_PeopleDetection_peopleDetectedPtr
newCallback_PeopleDetection_peopleDetected(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_PeopleDetection_peopleDetected<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_PeopleDetection_peopleDetectedPtr
newCallback_PeopleDetection_peopleDetected(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_PeopleDetection_peopleDetected<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_PeopleDetection_peopleDetectedPtr
newCallback_PeopleDetection_peopleDetected(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_PeopleDetection_peopleDetected<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_PeopleDetection_peopleDetectedPtr
newCallback_PeopleDetection_peopleDetected(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_PeopleDetection_peopleDetected<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_PeopleDetection_peopleDetected : public Callback_PeopleDetection_peopleDetected_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_PeopleDetection_peopleDetected(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_PeopleDetection_peopleDetectedPtr
newCallback_PeopleDetection_peopleDetected(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_PeopleDetection_peopleDetected<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_PeopleDetection_peopleDetectedPtr
newCallback_PeopleDetection_peopleDetected(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_PeopleDetection_peopleDetected<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_PeopleDetection_peopleDetectedPtr
newCallback_PeopleDetection_peopleDetected(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_PeopleDetection_peopleDetected<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_PeopleDetection_peopleDetectedPtr
newCallback_PeopleDetection_peopleDetected(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_PeopleDetection_peopleDetected<T, CT>(instance, 0, excb, sentcb);
}

}

#endif
