// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `PeopleDetection.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <PeopleDetection.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/BasicStream.h>
#include <Ice/Object.h>
#include <IceUtil/Iterator.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace
{

const ::std::string __RoboCompPeopleDetection__PeopleDetection__peopleDetected_name = "peopleDetected";

}
::IceProxy::Ice::Object* ::IceProxy::RoboCompPeopleDetection::upCast(::IceProxy::RoboCompPeopleDetection::PeopleDetection* p) { return p; }

void
::IceProxy::RoboCompPeopleDetection::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::RoboCompPeopleDetection::PeopleDetection>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::RoboCompPeopleDetection::PeopleDetection;
        v->__copyFrom(proxy);
    }
}

void
IceProxy::RoboCompPeopleDetection::PeopleDetection::peopleDetected(bool people, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __RoboCompPeopleDetection__PeopleDetection__peopleDetected_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __delBase = __getDelegate(false);
            ::IceDelegate::RoboCompPeopleDetection::PeopleDetection* __del = dynamic_cast< ::IceDelegate::RoboCompPeopleDetection::PeopleDetection*>(__delBase.get());
            __del->peopleDetected(people, __ctx, __observer);
            return;
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::RoboCompPeopleDetection::PeopleDetection::begin_peopleDetected(bool people, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RoboCompPeopleDetection__PeopleDetection__peopleDetected_name, __del, __cookie);
    try
    {
        __result->__prepare(__RoboCompPeopleDetection__PeopleDetection__peopleDetected_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(people);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

void
IceProxy::RoboCompPeopleDetection::PeopleDetection::end_peopleDetected(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __RoboCompPeopleDetection__PeopleDetection__peopleDetected_name);
}

const ::std::string&
IceProxy::RoboCompPeopleDetection::PeopleDetection::ice_staticId()
{
    return ::RoboCompPeopleDetection::PeopleDetection::ice_staticId();
}

::IceInternal::Handle< ::IceDelegateM::Ice::Object>
IceProxy::RoboCompPeopleDetection::PeopleDetection::__createDelegateM()
{
    return ::IceInternal::Handle< ::IceDelegateM::Ice::Object>(new ::IceDelegateM::RoboCompPeopleDetection::PeopleDetection);
}

::IceInternal::Handle< ::IceDelegateD::Ice::Object>
IceProxy::RoboCompPeopleDetection::PeopleDetection::__createDelegateD()
{
    return ::IceInternal::Handle< ::IceDelegateD::Ice::Object>(new ::IceDelegateD::RoboCompPeopleDetection::PeopleDetection);
}

::IceProxy::Ice::Object*
IceProxy::RoboCompPeopleDetection::PeopleDetection::__newInstance() const
{
    return new PeopleDetection;
}

void
IceDelegateM::RoboCompPeopleDetection::PeopleDetection::peopleDetected(bool people, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __RoboCompPeopleDetection__PeopleDetection__peopleDetected_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(people);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    if(__og.hasResponse())
    {
        try
        {
            if(!__ok)
            {
                try
                {
                    __og.throwUserException();
                }
                catch(const ::Ice::UserException& __ex)
                {
                    ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                    throw __uue;
                }
            }
            __og.readEmptyParams();
        }
        catch(const ::Ice::LocalException& __ex)
        {
            throw ::IceInternal::LocalExceptionWrapper(__ex, false);
        }
    }
}

void
IceDelegateD::RoboCompPeopleDetection::PeopleDetection::peopleDetected(bool people, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(bool __p_people, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _m_people(__p_people)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::RoboCompPeopleDetection::PeopleDetection* servant = dynamic_cast< ::RoboCompPeopleDetection::PeopleDetection*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            servant->peopleDetected(_m_people, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        bool _m_people;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __RoboCompPeopleDetection__PeopleDetection__peopleDetected_name, ::Ice::Normal, __context);
    try
    {
        _DirectI __direct(people, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
}

::Ice::Object* RoboCompPeopleDetection::upCast(::RoboCompPeopleDetection::PeopleDetection* p) { return p; }

namespace
{
const ::std::string __RoboCompPeopleDetection__PeopleDetection_ids[2] =
{
    "::Ice::Object",
    "::RoboCompPeopleDetection::PeopleDetection"
};

}

bool
RoboCompPeopleDetection::PeopleDetection::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__RoboCompPeopleDetection__PeopleDetection_ids, __RoboCompPeopleDetection__PeopleDetection_ids + 2, _s);
}

::std::vector< ::std::string>
RoboCompPeopleDetection::PeopleDetection::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__RoboCompPeopleDetection__PeopleDetection_ids[0], &__RoboCompPeopleDetection__PeopleDetection_ids[2]);
}

const ::std::string&
RoboCompPeopleDetection::PeopleDetection::ice_id(const ::Ice::Current&) const
{
    return __RoboCompPeopleDetection__PeopleDetection_ids[1];
}

const ::std::string&
RoboCompPeopleDetection::PeopleDetection::ice_staticId()
{
    return __RoboCompPeopleDetection__PeopleDetection_ids[1];
}

::Ice::DispatchStatus
RoboCompPeopleDetection::PeopleDetection::___peopleDetected(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    bool people;
    __is->read(people);
    __inS.endReadParams();
    peopleDetected(people, __current);
    __inS.__writeEmptyParams();
    return ::Ice::DispatchOK;
}

namespace
{
const ::std::string __RoboCompPeopleDetection__PeopleDetection_all[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "peopleDetected"
};

}

::Ice::DispatchStatus
RoboCompPeopleDetection::PeopleDetection::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__RoboCompPeopleDetection__PeopleDetection_all, __RoboCompPeopleDetection__PeopleDetection_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __RoboCompPeopleDetection__PeopleDetection_all)
    {
        case 0:
        {
            return ___ice_id(in, current);
        }
        case 1:
        {
            return ___ice_ids(in, current);
        }
        case 2:
        {
            return ___ice_isA(in, current);
        }
        case 3:
        {
            return ___ice_ping(in, current);
        }
        case 4:
        {
            return ___peopleDetected(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
RoboCompPeopleDetection::PeopleDetection::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
RoboCompPeopleDetection::PeopleDetection::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
RoboCompPeopleDetection::__patch(PeopleDetectionPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::RoboCompPeopleDetection::PeopleDetectionPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::RoboCompPeopleDetection::PeopleDetection::ice_staticId(), v);
    }
}
