// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `VelodyneData.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <VelodyneData.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/BasicStream.h>
#include <Ice/Object.h>
#include <IceUtil/Iterator.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace
{

const ::std::string __RoboCompVelodyneData__VelodyneData__personPosition_name = "personPosition";

}

namespace Ice
{
}
::IceProxy::Ice::Object* ::IceProxy::RoboCompVelodyneData::upCast(::IceProxy::RoboCompVelodyneData::VelodyneData* p) { return p; }

void
::IceProxy::RoboCompVelodyneData::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::RoboCompVelodyneData::VelodyneData>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::RoboCompVelodyneData::VelodyneData;
        v->__copyFrom(proxy);
    }
}

void
IceProxy::RoboCompVelodyneData::VelodyneData::personPosition(const ::RoboCompVelodyneData::personPose& p, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __RoboCompVelodyneData__VelodyneData__personPosition_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __delBase = __getDelegate(false);
            ::IceDelegate::RoboCompVelodyneData::VelodyneData* __del = dynamic_cast< ::IceDelegate::RoboCompVelodyneData::VelodyneData*>(__delBase.get());
            __del->personPosition(p, __ctx, __observer);
            return;
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::RoboCompVelodyneData::VelodyneData::begin_personPosition(const ::RoboCompVelodyneData::personPose& p, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RoboCompVelodyneData__VelodyneData__personPosition_name, __del, __cookie);
    try
    {
        __result->__prepare(__RoboCompVelodyneData__VelodyneData__personPosition_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(p);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

void
IceProxy::RoboCompVelodyneData::VelodyneData::end_personPosition(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __RoboCompVelodyneData__VelodyneData__personPosition_name);
}

const ::std::string&
IceProxy::RoboCompVelodyneData::VelodyneData::ice_staticId()
{
    return ::RoboCompVelodyneData::VelodyneData::ice_staticId();
}

::IceInternal::Handle< ::IceDelegateM::Ice::Object>
IceProxy::RoboCompVelodyneData::VelodyneData::__createDelegateM()
{
    return ::IceInternal::Handle< ::IceDelegateM::Ice::Object>(new ::IceDelegateM::RoboCompVelodyneData::VelodyneData);
}

::IceInternal::Handle< ::IceDelegateD::Ice::Object>
IceProxy::RoboCompVelodyneData::VelodyneData::__createDelegateD()
{
    return ::IceInternal::Handle< ::IceDelegateD::Ice::Object>(new ::IceDelegateD::RoboCompVelodyneData::VelodyneData);
}

::IceProxy::Ice::Object*
IceProxy::RoboCompVelodyneData::VelodyneData::__newInstance() const
{
    return new VelodyneData;
}

void
IceDelegateM::RoboCompVelodyneData::VelodyneData::personPosition(const ::RoboCompVelodyneData::personPose& p, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __RoboCompVelodyneData__VelodyneData__personPosition_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(p);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    if(__og.hasResponse())
    {
        try
        {
            if(!__ok)
            {
                try
                {
                    __og.throwUserException();
                }
                catch(const ::Ice::UserException& __ex)
                {
                    ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                    throw __uue;
                }
            }
            __og.readEmptyParams();
        }
        catch(const ::Ice::LocalException& __ex)
        {
            throw ::IceInternal::LocalExceptionWrapper(__ex, false);
        }
    }
}

void
IceDelegateD::RoboCompVelodyneData::VelodyneData::personPosition(const ::RoboCompVelodyneData::personPose& p, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(const ::RoboCompVelodyneData::personPose& __p_p, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _m_p(__p_p)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::RoboCompVelodyneData::VelodyneData* servant = dynamic_cast< ::RoboCompVelodyneData::VelodyneData*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            servant->personPosition(_m_p, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        const ::RoboCompVelodyneData::personPose& _m_p;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __RoboCompVelodyneData__VelodyneData__personPosition_name, ::Ice::Normal, __context);
    try
    {
        _DirectI __direct(p, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
}

::Ice::Object* RoboCompVelodyneData::upCast(::RoboCompVelodyneData::VelodyneData* p) { return p; }

namespace
{
const ::std::string __RoboCompVelodyneData__VelodyneData_ids[2] =
{
    "::Ice::Object",
    "::RoboCompVelodyneData::VelodyneData"
};

}

bool
RoboCompVelodyneData::VelodyneData::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__RoboCompVelodyneData__VelodyneData_ids, __RoboCompVelodyneData__VelodyneData_ids + 2, _s);
}

::std::vector< ::std::string>
RoboCompVelodyneData::VelodyneData::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__RoboCompVelodyneData__VelodyneData_ids[0], &__RoboCompVelodyneData__VelodyneData_ids[2]);
}

const ::std::string&
RoboCompVelodyneData::VelodyneData::ice_id(const ::Ice::Current&) const
{
    return __RoboCompVelodyneData__VelodyneData_ids[1];
}

const ::std::string&
RoboCompVelodyneData::VelodyneData::ice_staticId()
{
    return __RoboCompVelodyneData__VelodyneData_ids[1];
}

::Ice::DispatchStatus
RoboCompVelodyneData::VelodyneData::___personPosition(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::RoboCompVelodyneData::personPose p;
    __is->read(p);
    __inS.endReadParams();
    personPosition(p, __current);
    __inS.__writeEmptyParams();
    return ::Ice::DispatchOK;
}

namespace
{
const ::std::string __RoboCompVelodyneData__VelodyneData_all[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "personPosition"
};

}

::Ice::DispatchStatus
RoboCompVelodyneData::VelodyneData::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__RoboCompVelodyneData__VelodyneData_all, __RoboCompVelodyneData__VelodyneData_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __RoboCompVelodyneData__VelodyneData_all)
    {
        case 0:
        {
            return ___ice_id(in, current);
        }
        case 1:
        {
            return ___ice_ids(in, current);
        }
        case 2:
        {
            return ___ice_isA(in, current);
        }
        case 3:
        {
            return ___ice_ping(in, current);
        }
        case 4:
        {
            return ___personPosition(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
RoboCompVelodyneData::VelodyneData::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
RoboCompVelodyneData::VelodyneData::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
RoboCompVelodyneData::__patch(VelodyneDataPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::RoboCompVelodyneData::VelodyneDataPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::RoboCompVelodyneData::VelodyneData::ice_staticId(), v);
    }
}
